-- ==============================================================================
-- EDGEWFORCE — CANONICAL DATABASE SCHEMA, INDEXES, FUNCTIONS & RLS POLICIES
-- Production-Ready Multi-Tenant Enterprise Field-Force & Workforce Operating System
-- LEGACY ALTERNATE: Do not combine this file with supabase/migrations/*.sql.
-- It defines UUID employee primary keys, while the versioned migration chain
-- preserves legacy numeric employee IDs and adds UUID references alongside them.
-- For a new database, use supabase/migrations/all.sql instead.
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. COMPANIES (Multi-Tenancy Root)
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    business_type TEXT DEFAULT 'Distribution',
    industry TEXT DEFAULT 'FMCG',
    registration_number TEXT,
    email TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    country TEXT DEFAULT 'Nigeria',
    state TEXT DEFAULT 'Lagos',
    city TEXT DEFAULT 'Lagos',
    logo_url TEXT,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'suspended', 'onboarding')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT companies_uuid_unique UNIQUE(uuid),
    CONSTRAINT companies_email_unique UNIQUE(email)
);

-- 3. COMPANY SETTINGS
CREATE TABLE IF NOT EXISTS public.company_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT UNIQUE NOT NULL
        REFERENCES public.companies(id)
        ON DELETE CASCADE,
    working_days TEXT[] DEFAULT ARRAY[
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday'
    ],
    work_start_time TIME DEFAULT '08:30:00',
    work_end_time TIME DEFAULT '17:00:00',
    timezone TEXT DEFAULT 'Africa/Lagos',
    attendance_required BOOLEAN DEFAULT TRUE,
    location_tracking_enabled BOOLEAN DEFAULT TRUE,
    geofence_enabled BOOLEAN DEFAULT TRUE,
    geofence_radius_meters INTEGER DEFAULT 150,
    late_threshold_minutes INTEGER DEFAULT 15,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. PROFILES (Linked to auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY
        REFERENCES auth.users(id)
        ON DELETE CASCADE,
    company_id BIGINT
        REFERENCES public.companies(id)
        ON DELETE SET NULL,
    first_name TEXT,
    last_name TEXT,
    phone TEXT,
    avatar_url TEXT,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive', 'suspended')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. ROLES (Canonical Access Control)
CREATE TABLE IF NOT EXISTS public.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.roles (name, description)
VALUES
('super_admin', 'Platform Super Administrator'),
('agent_admin', 'Company Agent Administrator'),
('supervisor', 'Field Sales Supervisor'),
('sales_agent', 'Sales Agent'),
('field_agent', 'Field Agent'),
('hr_manager', 'Human Resources Manager'),
('staff', 'General Staff Member')
ON CONFLICT (name) DO NOTHING;

-- 6. EMPLOYEES
CREATE TABLE IF NOT EXISTS public.employees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID
        REFERENCES auth.users(id)
        ON DELETE SET NULL,
    company_id BIGINT NOT NULL
        REFERENCES public.companies(id)
        ON DELETE CASCADE,
    role_id BIGINT
        REFERENCES public.roles(id)
        ON DELETE SET NULL,
    employee_code TEXT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    job_title TEXT,
    department TEXT,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (
            status IN (
                'active',
                'inactive',
                'suspended',
                'terminated',
                'on_leave'
            )
        ),
    hire_date DATE,
    avatar_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(company_id, employee_code)
);

-- 7. MARKETS
CREATE TABLE IF NOT EXISTS public.markets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL
        REFERENCES public.companies(id)
        ON DELETE CASCADE,
    name TEXT NOT NULL,
    code TEXT,
    state TEXT,
    city TEXT,
    address TEXT,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(company_id, name)
);

-- 8. STORES / OUTLETS
CREATE TABLE IF NOT EXISTS public.stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL
        REFERENCES public.companies(id)
        ON DELETE CASCADE,
    market_id BIGINT
        REFERENCES public.markets(id)
        ON DELETE SET NULL,
    name TEXT NOT NULL,
    code TEXT,
    owner_name TEXT,
    phone TEXT,
    address TEXT,
    state TEXT,
    city TEXT,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    geofence_radius_meters INTEGER DEFAULT 150,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(company_id, code)
);

-- 9. PRODUCTS & SKUS
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL
        REFERENCES public.companies(id)
        ON DELETE CASCADE,
    sku TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    category TEXT,
    brand TEXT,
    unit TEXT DEFAULT 'piece',
    cost_price NUMERIC(15,2) DEFAULT 0,
    selling_price NUMERIC(15,2) DEFAULT 0,
    reorder_level INTEGER DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive')),
    image_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(company_id, sku)
);

-- 10. INVENTORY (Store & Warehouse Stock)
CREATE TABLE IF NOT EXISTS public.inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL
        REFERENCES public.companies(id)
        ON DELETE CASCADE,
    product_id BIGINT NOT NULL
        REFERENCES public.products(id)
        ON DELETE CASCADE,
    store_id BIGINT
        REFERENCES public.stores(id)
        ON DELETE CASCADE,
    quantity INTEGER NOT NULL DEFAULT 0,
    reserved_quantity INTEGER NOT NULL DEFAULT 0,
    available_quantity INTEGER
        GENERATED ALWAYS AS (quantity - reserved_quantity) STORED,
    last_restocked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(company_id, product_id, store_id)
);

-- 11. ATTENDANCE (Mandatory Foundation Table)
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL
        REFERENCES public.companies(id)
        ON DELETE CASCADE,
    employee_id UUID NOT NULL
        REFERENCES public.employees(id)
        ON DELETE CASCADE,
    attendance_date DATE NOT NULL DEFAULT CURRENT_DATE,
    clock_in TIMESTAMPTZ,
    clock_out TIMESTAMPTZ,
    clock_in_latitude NUMERIC(10,7),
    clock_in_longitude NUMERIC(10,7),
    clock_out_latitude NUMERIC(10,7),
    clock_out_longitude NUMERIC(10,7),
    clock_in_address TEXT,
    clock_out_address TEXT,
    clock_in_accuracy NUMERIC,
    clock_out_accuracy NUMERIC,
    clock_in_distance_from_store NUMERIC,
    clock_out_distance_from_store NUMERIC,
    status TEXT NOT NULL DEFAULT 'present'
        CHECK (
            status IN (
                'present',
                'late',
                'absent',
                'half_day',
                'leave',
                'holiday',
                'off_day'
            )
        ),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(company_id, employee_id, attendance_date)
);

-- 12. FIELD VISITS
CREATE TABLE IF NOT EXISTS public.field_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL
        REFERENCES public.companies(id)
        ON DELETE CASCADE,
    employee_id UUID NOT NULL
        REFERENCES public.employees(id)
        ON DELETE CASCADE,
    store_id BIGINT
        REFERENCES public.stores(id)
        ON DELETE SET NULL,
    visit_date DATE NOT NULL DEFAULT CURRENT_DATE,
    check_in TIMESTAMPTZ,
    check_out TIMESTAMPTZ,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    purpose TEXT,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'planned'
        CHECK (
            status IN (
                'planned',
                'in_progress',
                'completed',
                'cancelled'
            )
        ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 13. SALES
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL
        REFERENCES public.companies(id)
        ON DELETE CASCADE,
    employee_id UUID
        REFERENCES public.employees(id)
        ON DELETE SET NULL,
    store_id BIGINT
        REFERENCES public.stores(id)
        ON DELETE SET NULL,
    sale_reference TEXT NOT NULL,
    sale_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    subtotal NUMERIC(15,2) NOT NULL DEFAULT 0,
    discount NUMERIC(15,2) NOT NULL DEFAULT 0,
    tax NUMERIC(15,2) NOT NULL DEFAULT 0,
    total NUMERIC(15,2) NOT NULL DEFAULT 0,
    payment_method TEXT,
    status TEXT NOT NULL DEFAULT 'completed'
        CHECK (
            status IN (
                'draft',
                'pending',
                'completed',
                'cancelled',
                'refunded'
            )
        ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(company_id, sale_reference)
);

-- 14. SALE ITEMS
CREATE TABLE IF NOT EXISTS public.sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL
        REFERENCES public.sales(id)
        ON DELETE CASCADE,
    product_id BIGINT NOT NULL
        REFERENCES public.products(id)
        ON DELETE RESTRICT,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(15,2) NOT NULL DEFAULT 0,
    discount NUMERIC(15,2) NOT NULL DEFAULT 0,
    total NUMERIC(15,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 15. TASKS
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL
        REFERENCES public.companies(id)
        ON DELETE CASCADE,
    assigned_to UUID
        REFERENCES public.employees(id)
        ON DELETE SET NULL,
    assigned_by UUID
        REFERENCES public.employees(id)
        ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT,
    priority TEXT NOT NULL DEFAULT 'medium'
        CHECK (
            priority IN (
                'low',
                'medium',
                'high',
                'urgent'
            )
        ),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (
            status IN (
                'pending',
                'in_progress',
                'completed',
                'cancelled'
            )
        ),
    due_date TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 16. EXPENSES
CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL
        REFERENCES public.companies(id)
        ON DELETE CASCADE,
    employee_id UUID NOT NULL
        REFERENCES public.employees(id)
        ON DELETE CASCADE,
    amount NUMERIC(15,2) NOT NULL CHECK (amount >= 0),
    category TEXT NOT NULL,
    description TEXT,
    expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
    receipt_url TEXT,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (
            status IN (
                'pending',
                'approved',
                'rejected',
                'paid'
            )
        ),
    approved_by UUID
        REFERENCES public.employees(id)
        ON DELETE SET NULL,
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 17. NOTIFICATIONS
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT
        REFERENCES public.companies(id)
        ON DELETE CASCADE,
    user_id UUID NOT NULL
        REFERENCES auth.users(id)
        ON DELETE CASCADE,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'general',
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 18. AUDIT LOGS
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT
        REFERENCES public.companies(id)
        ON DELETE SET NULL,
    user_id UUID
        REFERENCES auth.users(id)
        ON DELETE SET NULL,
    action TEXT NOT NULL,
    table_name TEXT,
    record_id TEXT,
    old_data JSONB,
    new_data JSONB,
    ip_address INET,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==============================================================================
-- INDEXES
-- ==============================================================================

CREATE INDEX IF NOT EXISTS idx_profiles_company ON public.profiles(company_id);
CREATE INDEX IF NOT EXISTS idx_employees_company ON public.employees(company_id);
CREATE INDEX IF NOT EXISTS idx_employees_user ON public.employees(user_id);
CREATE INDEX IF NOT EXISTS idx_markets_company ON public.markets(company_id);
CREATE INDEX IF NOT EXISTS idx_stores_company ON public.stores(company_id);
CREATE INDEX IF NOT EXISTS idx_stores_market ON public.stores(market_id);
CREATE INDEX IF NOT EXISTS idx_products_company ON public.products(company_id);
CREATE INDEX IF NOT EXISTS idx_inventory_company ON public.inventory(company_id);
CREATE INDEX IF NOT EXISTS idx_inventory_product ON public.inventory(product_id);
CREATE INDEX IF NOT EXISTS idx_attendance_company ON public.attendance(company_id);
CREATE INDEX IF NOT EXISTS idx_attendance_employee ON public.attendance(employee_id);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON public.attendance(attendance_date);
CREATE INDEX IF NOT EXISTS idx_attendance_company_date ON public.attendance(company_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_field_visits_company ON public.field_visits(company_id);
CREATE INDEX IF NOT EXISTS idx_field_visits_employee ON public.field_visits(employee_id);
CREATE INDEX IF NOT EXISTS idx_sales_company ON public.sales(company_id);
CREATE INDEX IF NOT EXISTS idx_sales_employee ON public.sales(employee_id);
CREATE INDEX IF NOT EXISTS idx_sales_store ON public.sales(store_id);
CREATE INDEX IF NOT EXISTS idx_tasks_company ON public.tasks(company_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned ON public.tasks(assigned_to);
CREATE INDEX IF NOT EXISTS idx_expenses_company ON public.expenses(company_id);
CREATE INDEX IF NOT EXISTS idx_expenses_employee ON public.expenses(employee_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_company ON public.notifications(company_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_company ON public.audit_logs(company_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON public.audit_logs(user_id);

-- ==============================================================================
-- SECURITY HELPER FUNCTIONS (Non-recursive SECURITY DEFINER)
-- ==============================================================================

CREATE OR REPLACE FUNCTION public.get_my_company_id()
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
DECLARE
    cid BIGINT;
BEGIN
    SELECT company_id INTO cid
    FROM public.profiles
    WHERE id = auth.uid();

    IF cid IS NULL THEN
        SELECT company_id INTO cid
        FROM public.employees
        WHERE user_id = auth.uid();
    END IF;

    RETURN cid;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_my_employee_id()
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
DECLARE
    eid UUID;
BEGIN
    SELECT id INTO eid
    FROM public.employees
    WHERE user_id = auth.uid();

    RETURN eid;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
DECLARE
    rname TEXT;
BEGIN
    SELECT r.name INTO rname
    FROM public.employees e
    JOIN public.roles r ON r.id = e.role_id
    WHERE e.user_id = auth.uid();

    RETURN rname;
END;
$$;

CREATE OR REPLACE FUNCTION public.is_super_admin()
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
BEGIN
    RETURN (public.get_my_role() = 'super_admin');
END;
$$;

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) ACTIVATION
-- ==============================================================================

ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.markets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.field_visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- RLS POLICIES (Tenant Isolation & Role Authorization)
-- ==============================================================================

-- Companies
DROP POLICY IF EXISTS companies_isolation_policy ON public.companies;
CREATE POLICY companies_isolation_policy ON public.companies
    FOR ALL
    USING (id = public.get_my_company_id() OR public.is_super_admin());

-- Company Settings
DROP POLICY IF EXISTS company_settings_isolation_policy ON public.company_settings;
CREATE POLICY company_settings_isolation_policy ON public.company_settings
    FOR ALL
    USING (company_id = public.get_my_company_id() OR public.is_super_admin());

-- Profiles
DROP POLICY IF EXISTS profiles_self_and_tenant ON public.profiles;
CREATE POLICY profiles_self_and_tenant ON public.profiles
    FOR ALL
    USING (id = auth.uid() OR company_id = public.get_my_company_id() OR public.is_super_admin());

-- Roles (Publicly readable for authenticated users)
DROP POLICY IF EXISTS roles_read_policy ON public.roles;
CREATE POLICY roles_read_policy ON public.roles
    FOR SELECT
    TO authenticated
    USING (TRUE);

-- Employees
DROP POLICY IF EXISTS employees_tenant_policy ON public.employees;
CREATE POLICY employees_tenant_policy ON public.employees
    FOR ALL
    USING (company_id = public.get_my_company_id() OR public.is_super_admin());

-- Markets
DROP POLICY IF EXISTS markets_tenant_policy ON public.markets;
CREATE POLICY markets_tenant_policy ON public.markets
    FOR ALL
    USING (company_id = public.get_my_company_id() OR public.is_super_admin());

-- Stores
DROP POLICY IF EXISTS stores_tenant_policy ON public.stores;
CREATE POLICY stores_tenant_policy ON public.stores
    FOR ALL
    USING (company_id = public.get_my_company_id() OR public.is_super_admin());

-- Products
DROP POLICY IF EXISTS products_tenant_policy ON public.products;
CREATE POLICY products_tenant_policy ON public.products
    FOR ALL
    USING (company_id = public.get_my_company_id() OR public.is_super_admin());

-- Inventory
DROP POLICY IF EXISTS inventory_tenant_policy ON public.inventory;
CREATE POLICY inventory_tenant_policy ON public.inventory
    FOR ALL
    USING (company_id = public.get_my_company_id() OR public.is_super_admin());

-- Attendance
DROP POLICY IF EXISTS attendance_tenant_policy ON public.attendance;
CREATE POLICY attendance_tenant_policy ON public.attendance
    FOR ALL
    USING (
        company_id = public.get_my_company_id() AND (
            employee_id = public.get_my_employee_id() OR
            public.get_my_role() IN ('super_admin', 'agent_admin', 'supervisor', 'hr_manager')
        ) OR public.is_super_admin()
    );

-- Field Visits
DROP POLICY IF EXISTS field_visits_tenant_policy ON public.field_visits;
CREATE POLICY field_visits_tenant_policy ON public.field_visits
    FOR ALL
    USING (
        company_id = public.get_my_company_id() AND (
            employee_id = public.get_my_employee_id() OR
            public.get_my_role() IN ('super_admin', 'agent_admin', 'supervisor')
        ) OR public.is_super_admin()
    );

-- Sales
DROP POLICY IF EXISTS sales_tenant_policy ON public.sales;
CREATE POLICY sales_tenant_policy ON public.sales
    FOR ALL
    USING (
        company_id = public.get_my_company_id() AND (
            employee_id = public.get_my_employee_id() OR
            public.get_my_role() IN ('super_admin', 'agent_admin', 'supervisor')
        ) OR public.is_super_admin()
    );

-- Sale Items
DROP POLICY IF EXISTS sale_items_tenant_policy ON public.sale_items;
CREATE POLICY sale_items_tenant_policy ON public.sale_items
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.sales s
            WHERE s.id = public.sale_items.sale_id
            AND (s.company_id = public.get_my_company_id() OR public.is_super_admin())
        )
    );

-- Tasks
DROP POLICY IF EXISTS tasks_tenant_policy ON public.tasks;
CREATE POLICY tasks_tenant_policy ON public.tasks
    FOR ALL
    USING (
        company_id = public.get_my_company_id() AND (
            assigned_to = public.get_my_employee_id() OR
            assigned_by = public.get_my_employee_id() OR
            public.get_my_role() IN ('super_admin', 'agent_admin', 'supervisor', 'hr_manager')
        ) OR public.is_super_admin()
    );

-- Expenses
DROP POLICY IF EXISTS expenses_tenant_policy ON public.expenses;
CREATE POLICY expenses_tenant_policy ON public.expenses
    FOR ALL
    USING (
        company_id = public.get_my_company_id() AND (
            employee_id = public.get_my_employee_id() OR
            public.get_my_role() IN ('super_admin', 'agent_admin', 'supervisor', 'hr_manager')
        ) OR public.is_super_admin()
    );

-- Notifications
DROP POLICY IF EXISTS notifications_user_policy ON public.notifications;
CREATE POLICY notifications_user_policy ON public.notifications
    FOR ALL
    USING (user_id = auth.uid() OR public.is_super_admin());

-- Audit Logs
DROP POLICY IF EXISTS audit_logs_tenant_policy ON public.audit_logs;
CREATE POLICY audit_logs_tenant_policy ON public.audit_logs
    FOR ALL
    USING (company_id = public.get_my_company_id() OR public.is_super_admin());

-- ==============================================================================
-- TASK INTELLIGENCE, MULTI-CHANNEL REMINDERS & ACTIVITY TELEMETRY
-- ==============================================================================

-- Alter tasks table with intelligence columns
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS client_name VARCHAR(150);
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS project_name VARCHAR(150);
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS task_type VARCHAR(50) DEFAULT 'general';
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS delivery_stages JSONB DEFAULT NULL;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS due_at TIMESTAMPTZ;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS acknowledged_at TIMESTAMPTZ;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS acknowledged_by UUID;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS completed_by UUID;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS completion_notes TEXT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS evidence_url TEXT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS evidence_name VARCHAR(255);

-- 18. Task Reminders (Multi-channel proactive scheduling)
CREATE TABLE IF NOT EXISTS public.task_reminders (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    task_id BIGINT NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    employee_id UUID REFERENCES public.employees(id) ON DELETE SET NULL,
    reminder_at TIMESTAMPTZ NOT NULL,
    reminder_level VARCHAR(50) NOT NULL DEFAULT 'pre_deadline', -- pre_deadline, deadline, overdue, escalation
    channels JSONB NOT NULL DEFAULT '["in_app", "email", "whatsapp", "push"]'::jsonb,
    status VARCHAR(50) NOT NULL DEFAULT 'scheduled', -- scheduled, processing, sent, failed, cancelled
    attempts INTEGER NOT NULL DEFAULT 0,
    idempotency_key VARCHAR(100) UNIQUE,
    error_message TEXT,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 19. Reminder Delivery Logs
CREATE TABLE IF NOT EXISTS public.reminder_delivery_logs (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    reminder_id BIGINT REFERENCES public.task_reminders(id) ON DELETE SET NULL,
    task_id BIGINT NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    channel VARCHAR(50) NOT NULL, -- in_app, email, whatsapp, push
    status VARCHAR(50) NOT NULL, -- sent, failed, not_configured, suppressed
    provider_message_id VARCHAR(150),
    error_message TEXT,
    sent_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()),
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 20. Employee Idle Telemetry Sessions
CREATE TABLE IF NOT EXISTS public.employee_idle_sessions (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id UUID REFERENCES public.employees(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    idle_started_at TIMESTAMPTZ NOT NULL,
    detected_at TIMESTAMPTZ NOT NULL,
    duration_seconds INTEGER NOT NULL DEFAULT 600,
    reason VARCHAR(100) DEFAULT 'Awaiting Explanation',
    reason_details TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'pending', -- pending, explained, unexplained
    reported_to_it_at TIMESTAMPTZ,
    reported_to_hr_at TIMESTAMPTZ,
    workstation_snapshot JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 21. WORK LOCATIONS
CREATE TABLE IF NOT EXISTS public.work_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    location_type TEXT NOT NULL DEFAULT 'Office'
        CHECK (location_type IN (
            'Office', 'Market', 'Store', 'Supermarket', 'Client Location',
            'Warehouse', 'Branch', 'Distributor', 'Event Location', 'Other'
        )),
    address TEXT,
    state TEXT NOT NULL DEFAULT 'Lagos',
    lga TEXT,
    city TEXT,
    latitude NUMERIC(10,7) NOT NULL,
    longitude NUMERIC(10,7) NOT NULL,
    geofence_radius_meters INTEGER NOT NULL DEFAULT 150
        CHECK (geofence_radius_meters >= 20 AND geofence_radius_meters <= 10000),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT work_locations_company_name_unique UNIQUE(company_id, name)
);

-- 22. EMPLOYEE LOCATION ASSIGNMENTS
CREATE TABLE IF NOT EXISTS public.employee_location_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id UUID NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    location_id BIGINT NOT NULL REFERENCES public.work_locations(id) ON DELETE CASCADE,
    assignment_type TEXT NOT NULL DEFAULT 'primary'
        CHECK (assignment_type IN ('primary', 'secondary', 'temporary', 'permanent')),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    assigned_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 23. LOCATION ASSIGNMENT AUDIT HISTORY
CREATE TABLE IF NOT EXISTS public.location_assignment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id UUID NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    previous_location_id BIGINT REFERENCES public.work_locations(id) ON DELETE SET NULL,
    previous_location_name TEXT,
    new_location_id BIGINT REFERENCES public.work_locations(id) ON DELETE SET NULL,
    new_location_name TEXT,
    assignment_type TEXT NOT NULL DEFAULT 'primary',
    action TEXT NOT NULL DEFAULT 'ASSIGNED',
    changed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    changed_by_name TEXT,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS on new tables
ALTER TABLE public.task_reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reminder_delivery_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_idle_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_location_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.location_assignment_history ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Reminders & Logs
DROP POLICY IF EXISTS task_reminders_tenant_policy ON public.task_reminders;
CREATE POLICY task_reminders_tenant_policy ON public.task_reminders
    FOR ALL
    USING (company_id = public.get_my_company_id() OR public.is_super_admin());

DROP POLICY IF EXISTS reminder_delivery_logs_tenant_policy ON public.reminder_delivery_logs;
CREATE POLICY reminder_delivery_logs_tenant_policy ON public.reminder_delivery_logs
    FOR ALL
    USING (company_id = public.get_my_company_id() OR public.is_super_admin());

DROP POLICY IF EXISTS employee_idle_sessions_tenant_policy ON public.employee_idle_sessions;
CREATE POLICY employee_idle_sessions_tenant_policy ON public.employee_idle_sessions
    FOR ALL
    USING (company_id = public.get_my_company_id() OR public.is_super_admin());

DROP POLICY IF EXISTS work_locations_tenant_policy ON public.work_locations;
CREATE POLICY work_locations_tenant_policy ON public.work_locations
    FOR ALL
    USING (company_id = public.get_my_company_id() OR public.is_super_admin());

DROP POLICY IF EXISTS employee_location_assignments_tenant_policy ON public.employee_location_assignments;
CREATE POLICY employee_location_assignments_tenant_policy ON public.employee_location_assignments
    FOR ALL
    USING (company_id = public.get_my_company_id() OR public.is_super_admin());

DROP POLICY IF EXISTS location_assignment_history_tenant_policy ON public.location_assignment_history;
CREATE POLICY location_assignment_history_tenant_policy ON public.location_assignment_history
    FOR ALL
    USING (company_id = public.get_my_company_id() OR public.is_super_admin());

-- ==============================================================================
-- DEFAULT ENTERPRISE BASELINE SEED
-- ==============================================================================

INSERT INTO public.companies (id, name, business_type, industry, registration_number, email, phone, address, country, state, city, status)
VALUES (1, 'Experiential Edge Nigeria Limited', 'Commercial Operations', 'FMCG & Retail', 'RC-1849204', 'operations@edgewforce.com', '+2348030000001', '15 Atiba Osborne, Mende, Maryland', 'Nigeria', 'Lagos', 'Lagos', 'active')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email;

INSERT INTO public.company_settings (company_id, work_start_time, work_end_time, geofence_radius_meters, late_threshold_minutes)
VALUES (1, '08:30:00', '17:00:00', 150, 15)
ON CONFLICT (company_id) DO NOTHING;

-- ==============================================================================
-- 24. SUPABASE STORAGE BUCKET & POLICIES (edgewforce-media)
-- ==============================================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('edgewforce-media', 'edgewforce-media', true)
ON CONFLICT (id) DO NOTHING;

-- Allow public read access to uploaded media
DROP POLICY IF EXISTS "Public Access edgewforce-media" ON storage.objects;
CREATE POLICY "Public Access edgewforce-media" ON storage.objects
    FOR SELECT
    USING (bucket_id = 'edgewforce-media');

-- Allow authenticated and service uploads to media bucket
DROP POLICY IF EXISTS "Allow Uploads edgewforce-media" ON storage.objects;
CREATE POLICY "Allow Uploads edgewforce-media" ON storage.objects
    FOR INSERT
    WITH CHECK (bucket_id = 'edgewforce-media');



