-- ==============================================================================
-- EDGEWFORCE - SUPABASE POSTGRESQL INITIAL MIGRATION (001_initial_schema.sql)
-- Complete schema for Commercial Sales, Field Operations, HR, and Workforce Automation
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 0. COMPANIES (Tenant root)
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    name TEXT NOT NULL,
    business_type TEXT DEFAULT 'Commercial Operations',
    industry TEXT DEFAULT 'FMCG',
    registration_number TEXT,
    email TEXT UNIQUE,
    phone TEXT,
    address TEXT,
    logo_url TEXT,
    country TEXT DEFAULT 'Nigeria',
    state TEXT DEFAULT 'Lagos',
    city TEXT DEFAULT 'Lagos',
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'suspended', 'onboarding')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.companies (id, name, business_type, industry, email, phone, address)
VALUES
    (1, 'Experiential Edge Nigeria Limited', 'Commercial Operations', 'FMCG', 'operations@edgewforce.com', '+2348030000001', '15 Atiba Osborne, Mende, Maryland, Lagos'),
    (2, 'Apex FMCG', 'Commercial Operations', 'FMCG', 'jide@apexfmcg.ng', NULL, NULL)
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('public.companies', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM public.companies), 1), 1),
    true
);

-- 1. DEPARTMENTS
CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    code TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. RANKS (Organizational Hierarchy)
CREATE TABLE IF NOT EXISTS ranks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    level INTEGER NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. PERMISSIONS
CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. ROLE_PERMISSIONS
CREATE TABLE IF NOT EXISTS role_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code TEXT NOT NULL,
    permission_code TEXT NOT NULL REFERENCES permissions(code) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(role_code, permission_code)
);

-- 5. USERS
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE SET NULL,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    phone TEXT,
    role_code TEXT NOT NULL DEFAULT 'STAFF_MEMBER',
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'inactive', 'suspended')),
    avatar_url TEXT,
    requires_password_change BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. EMPLOYEES
CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id BIGINT UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    employee_code TEXT UNIQUE NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone TEXT,
    department_id BIGINT REFERENCES departments(id),
    department TEXT NOT NULL DEFAULT 'Operations',
    position TEXT NOT NULL,
    territory TEXT,
    rank_id BIGINT REFERENCES ranks(id),
    rank_code TEXT REFERENCES ranks(code),
    reporting_manager_id BIGINT REFERENCES employees(id),
    supervisor_id BIGINT REFERENCES employees(id),
    hire_date DATE NOT NULL DEFAULT CURRENT_DATE,
    base_salary NUMERIC(15,2) NOT NULL DEFAULT 350000.00,
    housing_allowance NUMERIC(15,2) NOT NULL DEFAULT 150000.00,
    transport_allowance NUMERIC(15,2) NOT NULL DEFAULT 75000.00,
    other_allowance NUMERIC(15,2) NOT NULL DEFAULT 25000.00,
    date_of_birth DATE,
    address TEXT,
    face_enrolled BOOLEAN NOT NULL DEFAULT FALSE,
    face_embedding_hash TEXT,
    emergency_contact_name TEXT,
    emergency_contact_phone TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. CUSTOMERS (Retailers, Outlets, Supermarkets, Distributors)
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    address TEXT NOT NULL,
    territory TEXT NOT NULL DEFAULT 'Lagos Mainland',
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    balance NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    credit_limit NUMERIC(15,2) NOT NULL DEFAULT 500000.00,
    registered_by BIGINT REFERENCES employees(id),
    birthday DATE,
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'inactive', 'blacklisted')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. PRODUCTS
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    unit TEXT NOT NULL DEFAULT 'carton',
    carton_pack_count INTEGER NOT NULL DEFAULT 24,
    price NUMERIC(15,2) NOT NULL,
    cost_price NUMERIC(15,2) NOT NULL,
    stock_quantity INTEGER NOT NULL DEFAULT 100,
    min_stock_alert INTEGER NOT NULL DEFAULT 15,
    description TEXT,
    image_url TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'inactive', 'discontinued')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. INVENTORY_TRANSACTIONS
CREATE TABLE IF NOT EXISTS inventory_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    change_quantity INTEGER NOT NULL,
    previous_quantity INTEGER NOT NULL,
    new_quantity INTEGER NOT NULL,
    type TEXT NOT NULL CHECK(type IN ('SALE', 'RESTOCK', 'ADJUSTMENT', 'RETURN', 'DAMAGE')),
    reference_id TEXT,
    notes TEXT,
    created_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. ORDERS
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number TEXT UNIQUE NOT NULL,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    sales_agent_id BIGINT NOT NULL REFERENCES employees(id),
    status TEXT NOT NULL DEFAULT 'confirmed' CHECK(status IN ('pending', 'confirmed', 'delivered', 'paid', 'cancelled')),
    subtotal NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    discount_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    vat_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00, -- 7.5%
    total_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    payment_method TEXT NOT NULL DEFAULT 'Bank Transfer' CHECK(payment_method IN ('Cash', 'Bank Transfer', 'POS Terminal', 'Cheque', 'Credit')),
    payment_status TEXT NOT NULL DEFAULT 'paid' CHECK(payment_status IN ('unpaid', 'partially_paid', 'paid')),
    notes TEXT,
    idempotency_key TEXT UNIQUE,
    order_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 11. ORDER_ITEMS
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL CHECK(quantity > 0),
    unit_price NUMERIC(15,2) NOT NULL,
    total_price NUMERIC(15,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 12. COLLECTIONS (Debt Payments)
CREATE TABLE IF NOT EXISTS collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    agent_id BIGINT NOT NULL REFERENCES employees(id),
    amount NUMERIC(15,2) NOT NULL CHECK(amount > 0),
    payment_method TEXT NOT NULL CHECK(payment_method IN ('Cash', 'Bank Transfer', 'POS Terminal', 'Cheque')),
    reference_number TEXT,
    notes TEXT,
    idempotency_key TEXT UNIQUE,
    payment_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 13. VISITS & ROUTE STOPS
CREATE TABLE IF NOT EXISTS visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL REFERENCES employees(id),
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    status TEXT NOT NULL DEFAULT 'scheduled' CHECK(status IN ('scheduled', 'in_progress', 'completed', 'missed', 'cancelled')),
    planned_time TIMESTAMPTZ,
    priority TEXT NOT NULL DEFAULT 'Normal' CHECK(priority IN ('URGENT', 'HIGH', 'NORMAL', 'Urgent', 'High', 'Normal')),
    check_in_time TIMESTAMPTZ,
    check_out_time TIMESTAMPTZ,
    duration_minutes INTEGER,
    check_in_lat NUMERIC(10,7),
    check_in_lng NUMERIC(10,7),
    check_in_distance_meters NUMERIC(10,2),
    is_geofence_verified BOOLEAN NOT NULL DEFAULT FALSE,
    photo_evidence_url TEXT,
    signature_url TEXT,
    shelf_share_percent INTEGER DEFAULT 50,
    out_of_stock_skus TEXT,
    competitor_notes TEXT,
    notes TEXT,
    idempotency_key TEXT UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 14. VISIT_AUDITS
CREATE TABLE IF NOT EXISTS visit_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id BIGINT NOT NULL REFERENCES visits(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    stock_status TEXT NOT NULL CHECK(stock_status IN ('Available', 'Low Stock', 'Out of Stock')),
    shelf_facing_count INTEGER DEFAULT 0,
    promo_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 15. COMPETITOR_INTEL
CREATE TABLE IF NOT EXISTS competitor_intel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL REFERENCES employees(id),
    customer_id BIGINT REFERENCES customers(id),
    competitor_brand TEXT NOT NULL,
    product_name TEXT NOT NULL,
    observed_price NUMERIC(15,2) NOT NULL,
    our_price NUMERIC(15,2) NOT NULL,
    price_difference NUMERIC(15,2) NOT NULL, -- observed_price - our_price
    shelf_share_percent INTEGER DEFAULT 50,
    promo_details TEXT,
    picture_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 16. ATTENDANCE
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    clock_in_time TIMESTAMPTZ,
    clock_out_time TIMESTAMPTZ,
    clock_in_lat NUMERIC(10,7),
    clock_in_lng NUMERIC(10,7),
    clock_in_accuracy NUMERIC(8,2),
    clock_in_device TEXT,
    clock_out_lat NUMERIC(10,7),
    clock_out_lng NUMERIC(10,7),
    clock_out_accuracy NUMERIC(8,2),
    clock_out_device TEXT,
    status TEXT NOT NULL DEFAULT 'Present' CHECK(status IN ('Present', 'Late', 'Absent', 'On Leave', 'Weekend', 'Holiday')),
    verification_mode TEXT NOT NULL DEFAULT 'GPS' CHECK(verification_mode IN ('GPS', 'FACIAL', 'MANUAL')),
    working_hours NUMERIC(5,2) DEFAULT 0.00,
    idempotency_key TEXT UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(employee_id, date)
);

-- 17. LEAVE_BALANCES
CREATE TABLE IF NOT EXISTS leave_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    year INTEGER NOT NULL DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
    annual INTEGER NOT NULL DEFAULT 20,
    sick INTEGER NOT NULL DEFAULT 12,
    casual INTEGER NOT NULL DEFAULT 5,
    maternity INTEGER NOT NULL DEFAULT 90,
    paternity INTEGER NOT NULL DEFAULT 5,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(employee_id, year)
);

-- 18. LEAVE_REQUESTS
CREATE TABLE IF NOT EXISTS leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    leave_type TEXT NOT NULL CHECK(leave_type IN ('Annual', 'Sick', 'Casual', 'Maternity', 'Paternity', 'Unpaid')),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    days INTEGER NOT NULL CHECK(days > 0),
    reason TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'approved', 'rejected', 'cancelled')),
    reviewed_by BIGINT REFERENCES employees(id),
    reviewed_at TIMESTAMPTZ,
    review_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 19. PAYSLIPS
CREATE TABLE IF NOT EXISTS payslips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    pay_month DATE NOT NULL,
    basic_salary NUMERIC(15,2) NOT NULL,
    housing_allowance NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    transport_allowance NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    other_allowance NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    gross_pay NUMERIC(15,2) NOT NULL,
    tax_paye NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    pension NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    other_deductions NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    total_deductions NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    net_pay NUMERIC(15,2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'published' CHECK(status IN ('draft', 'published', 'paid')),
    generated_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(employee_id, pay_month)
);

-- 20. OKRS & OKR_KEY_RESULTS
CREATE TABLE IF NOT EXISTS okrs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    year INTEGER NOT NULL DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
    quarter TEXT NOT NULL DEFAULT 'Q3',
    progress INTEGER NOT NULL DEFAULT 0 CHECK(progress >= 0 AND progress <= 100),
    status TEXT NOT NULL DEFAULT 'On Track' CHECK(status IN ('Not Started', 'On Track', 'At Risk', 'Completed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS okr_key_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    okr_id BIGINT NOT NULL REFERENCES okrs(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    target_value NUMERIC(15,2) NOT NULL DEFAULT 100.00,
    current_value NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    unit TEXT NOT NULL DEFAULT '%',
    progress INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 21. TASKS & TASK_COMMENTS
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    assigned_to BIGINT NOT NULL REFERENCES employees(id),
    assigned_by BIGINT NOT NULL REFERENCES users(id),
    department TEXT,
    priority TEXT NOT NULL DEFAULT 'Normal' CHECK(priority IN ('Urgent', 'High', 'Normal', 'Low', 'URGENT', 'HIGH', 'NORMAL')),
    due_date DATE,
    progress INTEGER NOT NULL DEFAULT 0 CHECK(progress >= 0 AND progress <= 100),
    status TEXT NOT NULL DEFAULT 'Pending' CHECK(status IN ('Pending', 'In Progress', 'Blocked', 'Completed', 'Cancelled', 'assigned', 'in_progress', 'completed')),
    attachment_url TEXT,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS task_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES users(id),
    comment TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 22. ANNOUNCEMENTS
CREATE TABLE IF NOT EXISTS announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    audience TEXT NOT NULL DEFAULT 'Everyone',
    priority TEXT NOT NULL DEFAULT 'Normal' CHECK(priority IN ('Urgent', 'High', 'Normal', 'Low')),
    start_date DATE DEFAULT CURRENT_DATE,
    end_date DATE,
    created_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 23. HOLIDAYS
CREATE TABLE IF NOT EXISTS holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    date DATE NOT NULL UNIQUE,
    description TEXT,
    year INTEGER NOT NULL DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 24. SETTLEMENTS
CREATE TABLE IF NOT EXISTS settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL REFERENCES employees(id),
    expected_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    amount NUMERIC(15,2) NOT NULL CHECK(amount >= 0),
    difference_amount NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    settlement_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    bank_slip_url TEXT,
    deposit_reference TEXT,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'submitted' CHECK(status IN ('pending', 'submitted', 'under_review', 'approved', 'rejected')),
    reviewed_by BIGINT REFERENCES users(id),
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 25. SOS_EVENTS
CREATE TABLE IF NOT EXISTS sos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL REFERENCES employees(id),
    latitude NUMERIC(10,7) NOT NULL,
    longitude NUMERIC(10,7) NOT NULL,
    accuracy NUMERIC(8,2),
    device_info TEXT,
    message TEXT NOT NULL DEFAULT 'Emergency SOS broadcast triggered',
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'acknowledged', 'resolved')),
    acknowledged_by BIGINT REFERENCES users(id),
    acknowledged_at TIMESTAMPTZ,
    resolved_by BIGINT REFERENCES users(id),
    resolved_at TIMESTAMPTZ,
    resolution_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 26. IDLE_EVENTS
CREATE TABLE IF NOT EXISTS idle_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    duration_seconds INTEGER NOT NULL DEFAULT 600,
    reason TEXT,
    explanation TEXT,
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    reviewed_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 27. PUSH_SUBSCRIPTIONS & NOTIFICATIONS
CREATE TABLE IF NOT EXISTS push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    endpoint TEXT NOT NULL,
    subscription_json TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(employee_id, endpoint)
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    type TEXT NOT NULL DEFAULT 'System' CHECK(type IN ('System', 'Tasks', 'Attendance', 'HR', 'Sales', 'Field', 'Emergency', 'SOS', 'Leave', 'Payment')),
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    link TEXT,
    read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 28. FACE_EVENTS
CREATE TABLE IF NOT EXISTS face_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL CHECK(event_type IN ('ENROLLMENT', 'VERIFICATION')),
    image_url TEXT,
    confidence NUMERIC(5,4),
    match_threshold NUMERIC(5,4) DEFAULT 0.80,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    provider TEXT NOT NULL DEFAULT 'INTERNAL_FACE_ENGINE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 29. AUDIT_LOGS
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT REFERENCES users(id),
    actor_email TEXT,
    action TEXT NOT NULL,
    entity TEXT NOT NULL,
    entity_id TEXT,
    metadata JSONB,
    ip_address TEXT,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 30. FILE_UPLOADS
CREATE TABLE IF NOT EXISTS file_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket TEXT NOT NULL DEFAULT 'edgewforce-assets',
    path TEXT NOT NULL,
    original_name TEXT,
    mime_type TEXT NOT NULL,
    size_bytes BIGINT NOT NULL,
    uploaded_by BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 31. AI_CONVERSATIONS & AI_MESSAGES
CREATE TABLE IF NOT EXISTS ai_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL DEFAULT 'Sales Copilot Session',
    context_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ai_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES ai_conversations(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK(role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 32. PERFORMANCE INDEXES
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_employees_user ON employees(user_id);
CREATE INDEX IF NOT EXISTS idx_employees_department ON employees(department_id);
CREATE INDEX IF NOT EXISTS idx_customers_code ON customers(code);
CREATE INDEX IF NOT EXISTS idx_products_sku ON products(sku);
CREATE INDEX IF NOT EXISTS idx_orders_agent_date ON orders(sales_agent_id, order_date);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_visits_agent_status ON visits(agent_id, status);
CREATE INDEX IF NOT EXISTS idx_attendance_employee_date ON attendance(employee_id, date);
CREATE INDEX IF NOT EXISTS idx_leave_employee_status ON leave_requests(employee_id, status);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to ON tasks(assigned_to, status);
CREATE INDEX IF NOT EXISTS idx_idle_open ON idle_alerts(resolved);
CREATE INDEX IF NOT EXISTS idx_sos_status ON sos(status);
CREATE INDEX IF NOT EXISTS idx_notifications_employee ON notifications(employee_id, read);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor ON audit_logs(actor_id, created_at);
