-- EDGEWFORCE: registration persistence prerequisites
-- Run this in the Supabase SQL Editor before enabling staff registration.

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    auth_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE SET NULL,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone TEXT UNIQUE,
    raw_phone TEXT,
    password_hash TEXT NOT NULL,
    role_code TEXT NOT NULL DEFAULT 'STAFF_MEMBER',
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
    avatar_url TEXT,
    requires_password_change BOOLEAN DEFAULT TRUE,
    password_changed_at TIMESTAMPTZ,
    first_login_at TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    onboarding_status TEXT DEFAULT 'Account Created',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.leave_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    year INTEGER NOT NULL,
    annual NUMERIC(8,2) NOT NULL DEFAULT 20,
    sick NUMERIC(8,2) NOT NULL DEFAULT 12,
    casual NUMERIC(8,2) NOT NULL DEFAULT 5,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(employee_id, year)
);

CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    business_name TEXT,
    customer_type TEXT DEFAULT 'Retail',
    tier TEXT DEFAULT 'Tier 1',
    territory TEXT DEFAULT 'Lagos Mainland',
    address TEXT,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    geofence_radius INTEGER DEFAULT 150,
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    credit_limit NUMERIC(15,2) DEFAULT 1000000.00,
    balance NUMERIC(15,2) DEFAULT 0.00,
    assigned_agent_id BIGINT,
    assigned_supervisor_id BIGINT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 001 creates the core customer table first; add the registration fields here
-- as ALTERs so this migration also works when that table already exists.
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS business_name TEXT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS customer_type TEXT DEFAULT 'Retail';
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS tier TEXT DEFAULT 'Tier 1';
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS geofence_radius INTEGER DEFAULT 150;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS assigned_agent_id BIGINT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS assigned_supervisor_id BIGINT;

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS auth_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS auth_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS position TEXT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS rank_code TEXT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS base_salary NUMERIC(15,2) DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_users_auth_user_id ON public.users(auth_user_id);
CREATE INDEX IF NOT EXISTS idx_employees_auth_user_id ON public.employees(auth_user_id);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role full access on users" ON public.users;
CREATE POLICY "Service role full access on users" ON public.users
FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role full access on employees" ON public.employees;
CREATE POLICY "Service role full access on employees" ON public.employees
FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Service role full access on customers" ON public.customers;
CREATE POLICY "Service role full access on customers" ON public.customers
FOR ALL TO service_role USING (true) WITH CHECK (true);

GRANT USAGE ON SCHEMA public TO service_role;
GRANT ALL ON TABLE public.users, public.employees, public.customers TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
