-- EDGEWFORCE: missing runtime tables and columns used by the Supabase backend.
-- References to employees/users use the UUID identities established by 011/012.

BEGIN;

CREATE TABLE IF NOT EXISTS public.company_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL UNIQUE REFERENCES public.companies(id) ON DELETE CASCADE,
  working_days TEXT[] NOT NULL DEFAULT ARRAY['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  working_hours_start TEXT DEFAULT '08:00',
  working_hours_end TEXT DEFAULT '17:00',
  work_start_time TIME DEFAULT '08:00',
  work_end_time TIME DEFAULT '17:00',
  timezone TEXT DEFAULT 'Africa/Lagos',
  attendance_required BOOLEAN NOT NULL DEFAULT TRUE,
  location_tracking_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  geofence_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  geofence_radius INTEGER DEFAULT 150,
  geofence_radius_meters INTEGER DEFAULT 150,
  late_threshold_minutes INTEGER DEFAULT 15,
  currency TEXT DEFAULT 'NGN',
  receipt_company_name TEXT,
  receipt_tagline TEXT,
  receipt_title TEXT,
  receipt_address TEXT,
  receipt_phone TEXT,
  receipt_footer_note TEXT,
  attendance_rules JSONB DEFAULT '{}'::jsonb,
  visit_rules JSONB DEFAULT '{}'::jsonb,
  sales_targets JSONB DEFAULT '{}'::jsonb,
  active_modules JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.company_settings (company_id, receipt_company_name, receipt_tagline, receipt_title, receipt_address, receipt_phone, receipt_footer_note)
SELECT 1, 'EXPERIENTIAL EDGE', 'Integrated Marketing & Commercial Distribution Solutions', 'EDGEWFORCE SALES RECEIPT', '15 Atiba Osborne, Mende, Maryland, Lagos', '+2348031234567', 'Thank you for your business.'
WHERE EXISTS (SELECT 1 FROM public.companies WHERE id = 1)
ON CONFLICT (company_id) DO NOTHING;

ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS registration_number TEXT;
ALTER TABLE public.companies ADD COLUMN IF NOT EXISTS logo_url TEXT;

CREATE TABLE IF NOT EXISTS public.roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.roles (name, description) VALUES
  ('super_admin', 'Platform Super Administrator'),
  ('admin', 'Company Administrator'),
  ('hr_manager', 'Human Resources Manager'),
  ('manager', 'Operations Manager'),
  ('supervisor', 'Field Operations Supervisor'),
  ('sales_agent', 'Sales Agent'),
  ('field_agent', 'Field Agent'),
  ('staff_member', 'Staff Member')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.regions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (company_id, code)
);

CREATE TABLE IF NOT EXISTS public.territories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  region_id BIGINT REFERENCES public.regions(id) ON DELETE SET NULL,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (company_id, code)
);

CREATE TABLE IF NOT EXISTS public.teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  code TEXT,
  department TEXT,
  region_id BIGINT REFERENCES public.regions(id) ON DELETE SET NULL,
  territory_id BIGINT REFERENCES public.territories(id) ON DELETE SET NULL,
  supervisor_id UUID REFERENCES public.employees(uuid) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  code TEXT,
  address TEXT,
  state TEXT,
  city TEXT,
  manager_id UUID REFERENCES public.employees(uuid) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.warehouses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  code TEXT,
  address TEXT,
  state TEXT,
  city TEXT,
  latitude NUMERIC(10,7),
  longitude NUMERIC(10,7),
  manager_id UUID REFERENCES public.employees(uuid) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.stores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  store_type TEXT DEFAULT 'Supermarket',
  contact_person TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  territory TEXT,
  latitude NUMERIC(10,7),
  longitude NUMERIC(10,7),
  geofence_radius INTEGER NOT NULL DEFAULT 150,
  supervisor_id UUID REFERENCES public.employees(uuid) ON DELETE SET NULL,
  assigned_field_agents UUID[] NOT NULL DEFAULT ARRAY[]::UUID[],
  assigned_sales_agents UUID[] NOT NULL DEFAULT ARRAY[]::UUID[],
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (company_id, code)
);

CREATE TABLE IF NOT EXISTS public.inventory_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  warehouse_id BIGINT REFERENCES public.warehouses(id) ON DELETE SET NULL,
  movement_type TEXT NOT NULL,
  quantity NUMERIC(14,3) NOT NULL,
  previous_quantity NUMERIC(14,3) NOT NULL DEFAULT 0,
  new_quantity NUMERIC(14,3) NOT NULL DEFAULT 0,
  reference_number TEXT,
  notes TEXT,
  recorded_by BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
  alert_type TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'MEDIUM',
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ,
  resolved_by UUID REFERENCES public.users(uuid) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  order_id BIGINT NOT NULL UNIQUE REFERENCES public.orders(id) ON DELETE CASCADE,
  customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
  driver_name TEXT,
  driver_phone TEXT,
  vehicle_number TEXT,
  dispatch_time TIMESTAMPTZ,
  actual_delivery_time TIMESTAMPTZ,
  delivery_status TEXT NOT NULL DEFAULT 'PENDING',
  recipient_name TEXT,
  recipient_signature TEXT,
  proof_of_delivery_photo TEXT,
  failure_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.order_approvals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  approver_id BIGINT,
  action TEXT NOT NULL,
  comments TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.store_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  store_name TEXT NOT NULL,
  address TEXT NOT NULL,
  store_type TEXT NOT NULL DEFAULT 'Supermarket',
  contact_person TEXT,
  phone TEXT,
  latitude NUMERIC(10,7) NOT NULL,
  longitude NUMERIC(10,7) NOT NULL,
  accuracy NUMERIC(8,2),
  requested_by UUID REFERENCES public.employees(uuid) ON DELETE SET NULL,
  supervisor_id UUID REFERENCES public.employees(uuid) ON DELETE SET NULL,
  reviewed_by UUID REFERENCES public.employees(uuid) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  store_photo_url TEXT,
  storefront_photo_url TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  geofence_radius INTEGER NOT NULL DEFAULT 150,
  territory TEXT,
  rejection_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES public.employees(uuid) ON DELETE CASCADE,
  employee_name TEXT,
  employee_code TEXT,
  department TEXT,
  position TEXT,
  date DATE NOT NULL,
  title TEXT,
  shift_start TEXT,
  shift_end TEXT,
  work_location TEXT,
  tasks JSONB NOT NULL DEFAULT '[]'::jsonb,
  total_planned_hours NUMERIC(6,2) DEFAULT 0,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'SUBMITTED',
  submitted_at TIMESTAMPTZ,
  supervisor_id UUID REFERENCES public.employees(uuid) ON DELETE SET NULL,
  supervisor_name TEXT,
  supervisor_status TEXT DEFAULT 'PENDING',
  supervisor_reviewed_at TIMESTAMPTZ,
  supervisor_notes TEXT,
  hr_status TEXT DEFAULT 'PENDING',
  hr_reviewed_at TIMESTAMPTZ,
  hr_notes TEXT,
  assigned_agent_id UUID REFERENCES public.employees(uuid) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (employee_id, date)
);

CREATE TABLE IF NOT EXISTS public.location_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL REFERENCES public.employees(uuid) ON DELETE CASCADE,
  employee_name TEXT,
  role TEXT,
  assigned_market TEXT,
  assigned_region TEXT,
  assigned_state TEXT,
  supervisor_id UUID REFERENCES public.employees(uuid) ON DELETE SET NULL,
  store_id BIGINT REFERENCES public.stores(id) ON DELETE SET NULL,
  location_id BIGINT REFERENCES public.work_locations(id) ON DELETE SET NULL,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  server_timestamp TIMESTAMPTZ,
  local_time_lagos TIMESTAMPTZ,
  latitude NUMERIC(10,7),
  longitude NUMERIC(10,7),
  accuracy NUMERIC(8,2),
  address TEXT,
  current_activity TEXT,
  activity TEXT,
  attendance_type TEXT,
  attendance_id BIGINT REFERENCES public.attendance(id) ON DELETE SET NULL,
  is_inside_geofence BOOLEAN,
  distance_from_store NUMERIC(12,2),
  geofence_status TEXT,
  status TEXT,
  notes TEXT,
  battery_level NUMERIC(5,2),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.location_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  employee_id UUID REFERENCES public.employees(uuid) ON DELETE SET NULL,
  supervisor_id UUID REFERENCES public.employees(uuid) ON DELETE SET NULL,
  alert_type TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'warning',
  message TEXT NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'active',
  resolved_by UUID REFERENCES public.users(uuid) ON DELETE SET NULL,
  resolved_at TIMESTAMPTZ,
  resolution_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.field_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id UUID NOT NULL REFERENCES public.employees(uuid) ON DELETE CASCADE,
  role TEXT,
  store_id BIGINT REFERENCES public.stores(id) ON DELETE SET NULL,
  visit_id BIGINT REFERENCES public.visits(id) ON DELETE SET NULL,
  activity_type TEXT NOT NULL,
  title TEXT,
  description TEXT,
  photo_url TEXT,
  latitude NUMERIC(10,7),
  longitude NUMERIC(10,7),
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.sales_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id UUID NOT NULL REFERENCES public.employees(uuid) ON DELETE CASCADE,
  store_id BIGINT REFERENCES public.stores(id) ON DELETE SET NULL,
  customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
  visit_id BIGINT REFERENCES public.visits(id) ON DELETE SET NULL,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
  activity_type TEXT NOT NULL,
  units_sold NUMERIC(14,3) NOT NULL DEFAULT 0,
  amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  notes TEXT,
  photo_url TEXT,
  latitude NUMERIC(10,7),
  longitude NUMERIC(10,7),
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.daily_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  supervisor_id UUID REFERENCES public.employees(uuid) ON DELETE SET NULL,
  total_members INTEGER NOT NULL DEFAULT 0,
  field_agents INTEGER NOT NULL DEFAULT 0,
  sales_agents INTEGER NOT NULL DEFAULT 0,
  present INTEGER NOT NULL DEFAULT 0,
  absent INTEGER NOT NULL DEFAULT 0,
  late INTEGER NOT NULL DEFAULT 0,
  geofence_violations INTEGER NOT NULL DEFAULT 0,
  missing_checkouts INTEGER NOT NULL DEFAULT 0,
  store_visits INTEGER NOT NULL DEFAULT 0,
  tasks_completed INTEGER NOT NULL DEFAULT 0,
  photos_uploaded INTEGER NOT NULL DEFAULT 0,
  sales_generated NUMERIC(15,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (date, supervisor_id)
);

CREATE TABLE IF NOT EXISTS public.task_reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
  task_id BIGINT NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.users(uuid) ON DELETE SET NULL,
  employee_id UUID REFERENCES public.employees(uuid) ON DELETE SET NULL,
  reminder_at TIMESTAMPTZ NOT NULL,
  reminder_level TEXT NOT NULL DEFAULT 'pre_deadline',
  channels JSONB NOT NULL DEFAULT '["in_app", "email", "whatsapp", "push"]'::jsonb,
  status TEXT NOT NULL DEFAULT 'scheduled',
  attempts INTEGER NOT NULL DEFAULT 0,
  idempotency_key TEXT UNIQUE,
  error_message TEXT,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.reminder_delivery_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
  reminder_id BIGINT REFERENCES public.task_reminders(id) ON DELETE SET NULL,
  task_id BIGINT NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.users(uuid) ON DELETE SET NULL,
  channel TEXT NOT NULL,
  status TEXT NOT NULL,
  provider_message_id TEXT,
  error_message TEXT,
  sent_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.employee_idle_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
  employee_id UUID REFERENCES public.employees(uuid) ON DELETE CASCADE,
  user_id UUID REFERENCES public.users(uuid) ON DELETE SET NULL,
  idle_started_at TIMESTAMPTZ NOT NULL,
  detected_at TIMESTAMPTZ NOT NULL,
  duration_seconds INTEGER NOT NULL DEFAULT 600,
  reason TEXT DEFAULT 'Awaiting Explanation',
  reason_details TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  reported_to_it_at TIMESTAMPTZ,
  reported_to_hr_at TIMESTAMPTZ,
  workstation_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.products ADD COLUMN IF NOT EXISTS company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS quantity_display TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS reorder_level INTEGER NOT NULL DEFAULT 20;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS warehouse_name TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS location_of_item TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS condition TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS shelf_number TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS shelve_location TEXT;

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS delivery_status TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS approved_by BIGINT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS rejection_reason TEXT;
ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS orders_status_check;
ALTER TABLE public.orders ADD CONSTRAINT orders_status_check
  CHECK (status IN ('pending', 'confirmed', 'delivered', 'paid', 'cancelled', 'DRAFT', 'APPROVED', 'REJECTED', 'DISPATCHED', 'DELIVERED'));

ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS department_id BIGINT REFERENCES public.departments(id) ON DELETE SET NULL;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS supervisor_id UUID;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS client_name TEXT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS project_name TEXT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS task_type TEXT NOT NULL DEFAULT 'general';
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS delivery_stages JSONB;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS due_at TIMESTAMPTZ;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS acknowledged_at TIMESTAMPTZ;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS acknowledged_by BIGINT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS completed_by BIGINT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS completion_notes TEXT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS evidence_url TEXT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS evidence_name TEXT;
ALTER TABLE public.tasks DROP CONSTRAINT IF EXISTS tasks_status_check;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_status_check
  CHECK (status IN ('Pending', 'In Progress', 'Blocked', 'Completed', 'Cancelled', 'assigned', 'in_progress', 'completed', 'pending', 'blocked', 'cancelled'));
ALTER TABLE public.tasks DROP CONSTRAINT IF EXISTS tasks_priority_check;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_priority_check
  CHECK (priority IN ('Urgent', 'High', 'Normal', 'Low', 'URGENT', 'HIGH', 'NORMAL', 'urgent', 'high', 'normal', 'low'));

ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS supervisor_id UUID REFERENCES public.employees(uuid) ON DELETE SET NULL;
ALTER TABLE public.work_locations ADD COLUMN IF NOT EXISTS geofence_radius INTEGER;
UPDATE public.work_locations SET geofence_radius = geofence_radius_meters WHERE geofence_radius IS NULL;
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_inventory_movements_company_created ON public.inventory_movements(company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_deliveries_company_status ON public.deliveries(company_id, delivery_status);
CREATE INDEX IF NOT EXISTS idx_schedules_employee_date ON public.schedules(employee_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_location_logs_employee_time ON public.location_logs(employee_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_location_logs_company_time ON public.location_logs(company_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_location_alerts_company_status ON public.location_alerts(company_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_store_requests_company_status ON public.store_requests(company_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_task_reminders_due ON public.task_reminders(status, reminder_at);
CREATE INDEX IF NOT EXISTS idx_reminder_logs_task_created ON public.reminder_delivery_logs(task_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_idle_sessions_company_detected ON public.employee_idle_sessions(company_id, detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_field_activities_employee_time ON public.field_activities(employee_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_sales_activities_employee_time ON public.sales_activities(employee_id, timestamp DESC);

DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'company_settings', 'roles', 'regions', 'territories', 'teams', 'branches', 'warehouses',
    'stores', 'inventory_movements', 'alerts', 'deliveries', 'order_approvals', 'store_requests',
    'schedules', 'location_logs', 'location_alerts', 'field_activities', 'sales_activities',
    'daily_summaries', 'task_reminders', 'reminder_delivery_logs', 'employee_idle_sessions'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('GRANT ALL ON TABLE public.%I TO service_role', table_name);
  END LOOP;
END;
$$;

GRANT SELECT ON public.company_settings TO authenticated;
GRANT SELECT ON public.work_locations, public.stores TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

INSERT INTO storage.buckets (id, name, public)
VALUES ('edgewforce-media', 'edgewforce-media', TRUE)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public Access edgewforce-media" ON storage.objects;
CREATE POLICY "Public Access edgewforce-media" ON storage.objects
FOR SELECT USING (bucket_id = 'edgewforce-media');

DROP POLICY IF EXISTS "Allow Uploads edgewforce-media" ON storage.objects;
CREATE POLICY "Allow Uploads edgewforce-media" ON storage.objects
FOR INSERT TO authenticated WITH CHECK (bucket_id = 'edgewforce-media');

COMMIT;
